---
abstract: 'simple CPAN package extractor'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.47'
  Test::UseAllModules: '0.10'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.06'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-Any-Lite
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Tar: '1.76'
  Archive::Zip: '0'
  File::Spec: '0'
  IO::Uncompress::Bunzip2: '0'
  IO::Zlib: '0'
resources:
  repository: https://github.com/charsbar/archive-any-lite
version: '0.08'
